### ISSUE TITLE
Remove quarters from `best fit`

### ISSUE THREAD

**Issue by zbraniecki** [caridy/proposal-intl-relative-time#12]
In the current spec language quarters will never be selected by the `GetBestMatchUnit` because they overlap `months`.

I suggest that we remove it from the `best fit` scenario, and leave it only for manual selection with `{unit: 'quarter'}`.

**Comment by caridy** [comment]
If we remove `best fit` entirely, then this is not a problem. Let's way for that to clear up, so we know what to do.
