### ISSUE TITLE
Textual names like "yesterday"

### ISSUE THREAD

**Issue by littledan** [caridy/proposal-intl-relative-time#27]
The ICU interface for getting at these times exposes strings like "yesterday" through a separate UDAT_ABSOLUTE_DAY unit. On the other hand, if you make an ordinary UDAT_RELATIVE_DAYS query for -1 days, you'll get "1 day ago". A couple questions about this:
- The current spec text says, first get the PluralRules, then select the template based on the PluralRules and direction, then fill it in. However, this would not allow getting something like "anteayer" (the day before yesterday) in Spanish because Spanish has no dual category; further, in English, it seems like a natural template to select would be "{0} day ago", rather than "yesterday". Do we want to use the ABSOLUTE version when available, falling back to the RELATIVE one only when appropriate?
- Are there any applications that would *want* to render as "1 day ago", or would really everybody want to render as "yesterday"? If so, maybe we should introduce separate "text" vs "numeric" modes, where "text" mode would use ABSOLUTE where applicable and fall back to RELATIVE if needed, and "numeric" would just start with RELATIVE. But something I don't understand is, does anyone want "numeric"?

**Comment by littledan** [comment]
cc @caridy @zbraniecki

**Comment by rxaviers** [comment]
@littledan can we close this issue?
