### ISSUE TITLE
"rt" and "pr" extension keys don't exist

### ISSUE THREAD

**Issue by zbraniecki** [caridy/proposal-intl-relative-time#8]
Current version of the spec specifies two relevant extension keys:

```
 The value of the [[RelevantExtensionKeys]] internal slot is ["rt", "pr"].
Note 1 Unicode Technical Standard 35 describes three locale extension keys that are relevant to relative time formatting, "rt" for relative time, and "pr" language plural rules to choose the proper relative time pattern. 
```

yet TR35 does not have either of those:

http://www.unicode.org/reports/tr35/#Locale_Extension_Key_and_Type_Data

Should we remove them?

**Comment by caridy** [comment]
Yes, let's remove that.

**Comment by caridy** [comment]
Note, if we will add the calendar option (from #13) we might need to add `ca` to the extension keys.
